# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr: 
- main
# pool:
#   vmImage: 'ubuntu-1604'

parameters:
  - name: create_release
    displayName: Create Release
    type: boolean
    default: false

steps:
# - script: echo Welcome to azure pipeline!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: GitHubRelease@1
  condition: eq('${{ parameters.create_release }}', true)
  inputs:
    gitHubConnection: 'github.com_shivamgupta-sg'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'main-*'
    title: 'testing github release'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
