# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr: 
- main
# pool:
#   vmImage: 'ubuntu-1604'

parameters:
  - name: create_release
    displayName: Create Release
    type: boolean
    default: false

variables:
  - name: majorVersion
    value: 1
  - name: minorVersion
    value: 0
  - name: patchVersion
    value: 0

steps:
# - script: echo Welcome to azure pipeline!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# - task: GitHubRelease@1
#   condition: eq('${{ parameters.create_release }}', true)
#   inputs:
#     gitHubConnection: 'github.com_shivamgupta-sg'
#     repositoryName: '$(Build.Repository.Name)'
#     action: 'create'
#     target: 'main-$(Build.SourceVersion)'
#     tagSource: 'gitTag'
#     tagPattern: 'main-*'
#     title: 'testing github release'
#     changeLogCompareToRelease: 'lastFullRelease'
#     changeLogType: 'commitBased'

- task: GitHubRelease@1
  condition: eq('${{ parameters.create_release }}', true)
  inputs:
    gitHubConnection: 'github.com_shivamgupta-sg'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'stable'
    title: 'stable release'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_shivamgupta-sg'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'stable'
    title: 'stable release'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_shivamgupta-sg'
    repositoryName: '$(Build.Repository.Name)'
    action: 'delete'
    tag: 'test_V1'